from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
import time
from threading import Thread

class Ui_MainWindow(object):

    def button_start(self):
        
        GPX_BROWSE = self.plainTextEdit.toPlainText()
        gpx_file = open('Gpx_browse.txt', 'w')
        gpx_file.write(GPX_BROWSE)
        gpx_file.close()
        
        MOTO1COM = self.comboBox.currentText()
        com1 = open('Moto1com.txt', 'w')
        com1.write(MOTO1COM)
        com1.close()

        MOTO2COM = self.comboBox_2.currentText()
        com2 = open('Moto2com.txt', 'w')
        com2.write(MOTO2COM)
        com2.close()

        MOTO3COM = self.comboBox_3.currentText()
        com3 = open('Moto3com.txt', 'w')
        com3.write(MOTO3COM)
        com3.close()

        MOTO4COM = self.comboBox_4.currentText()
        com4 = open('Moto4com.txt', 'w')
        com4.write(MOTO4COM)
        com4.close()

        HELICOPTERCOM = self.comboBox_5.currentText()
        com5 = open('Helicoptercom.txt', 'w')
        com5.write(HELICOPTERCOM)
        com5.close()

        AIRPLANECOM = self.comboBox_6.currentText()
        com6 = open('Airplanecom.txt', 'w')
        com6.write(AIRPLANECOM)
        com6.close()

        BAUD_RATE = self.comboBox_7.currentText()
        baud_rate_file = open('Baudrate.txt', 'w')
        baud_rate_file.write(BAUD_RATE)
        baud_rate_file.close()

        LATITUDE_GUEST = self.textEdit.toPlainText()
        latitudde_guest_file = open('Latitude_guest.txt', 'w')
        latitudde_guest_file.write(LATITUDE_GUEST)
        latitudde_guest_file.close()

        LONGITUDE_GUEST = self.textEdit_2.toPlainText()
        longitude_guest_file = open('Longitude_guest.txt', 'w')
        longitude_guest_file.write(LONGITUDE_GUEST)
        longitude_guest_file.close()

        

        def func1():
            subprocess.run("python map.py")

        def func2():
            subprocess.run("python3 loop.py")
        
        Thread(target= func1).start()
        Thread(target= func2).start()
        
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 478)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 141, 51))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 80, 241, 41))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 211, 71))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 180, 241, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 240, 241, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(370, 50, 131, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(490, 40, 20, 311))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(370, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(370, 150, 131, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(370, 200, 131, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(370, 250, 131, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(370, 300, 131, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 370, 151, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.button_start)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(510, 60, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(510, 110, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(510, 210, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(510, 160, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(510, 310, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(510, 260, 69, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 310, 101, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(120, 310, 71, 31))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(80, 370, 69, 22))
        self.comboBox_8.setObjectName("comboBox")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 370, 51, 21))
        self.label_5.setFont(font)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Zoom"))
        self.label.setText(_translate("MainWindow", "Import GPX file"))
        self.label_2.setText(_translate("MainWindow", "Coordinates of the race"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Latitude</p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Longitude</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "Moto 1"))
        self.checkBox_2.setText(_translate("MainWindow", "Moto 2"))
        self.checkBox_3.setText(_translate("MainWindow", "Moto 3"))
        self.checkBox_4.setText(_translate("MainWindow", "Moto 4"))
        self.checkBox_5.setText(_translate("MainWindow", "Aireplane"))
        self.checkBox_6.setText(_translate("MainWindow", "Helicopter"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.comboBox.setItemText(0, _translate("MainWindow", "NO"))
        self.comboBox.setItemText(1, _translate("MainWindow", "COM1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "COM2"))
        self.comboBox.setItemText(3, _translate("MainWindow", "COM3"))
        self.comboBox.setItemText(4, _translate("MainWindow", "COM4"))
        self.comboBox.setItemText(5, _translate("MainWindow", "COM5"))
        self.comboBox.setItemText(6, _translate("MainWindow", "COM6"))
        self.comboBox.setItemText(7, _translate("MainWindow", "COM7"))
        self.comboBox.setItemText(8, _translate("MainWindow", "COM8"))
        self.comboBox.setItemText(9, _translate("MainWindow", "COM9"))
        self.comboBox.setItemText(10, _translate("MainWindow", "COM10"))
        self.comboBox.setItemText(11, _translate("MainWindow", "COM11"))
        self.comboBox.setItemText(12, _translate("MainWindow", "COM12"))
        self.comboBox.setItemText(13, _translate("MainWindow", "COM13"))
        self.comboBox.setItemText(14, _translate("MainWindow", "COM15"))
        self.comboBox.setItemText(15, _translate("MainWindow", "COM16"))
        self.comboBox.setItemText(16, _translate("MainWindow", "COM17"))
        self.comboBox.setItemText(17, _translate("MainWindow", "COM18"))
        self.comboBox.setItemText(18, _translate("MainWindow", "COM19"))
        self.comboBox.setItemText(19, _translate("MainWindow", "COM20"))
        self.label_3.setText(_translate("MainWindow", "COM"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "NO"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "COM1"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "COM2"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "COM3"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "COM4"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "COM5"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "COM6"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "COM7"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "COM8"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "COM9"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "COM10"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "COM11"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "COM12"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "COM13"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "COM15"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "COM16"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "COM17"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "COM18"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "COM19"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "COM20"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "NO"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "COM1"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "COM2"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "COM3"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "COM4"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "COM5"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "COM6"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "COM7"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "COM8"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "COM9"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "COM10"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "COM11"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "COM12"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "COM13"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "COM15"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "COM16"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "COM17"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "COM18"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "COM19"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "COM20"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "NO"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "COM1"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "COM2"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "COM3"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "COM4"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "COM5"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "COM6"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "COM7"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "COM8"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "COM9"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "COM10"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "COM11"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "COM12"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "COM13"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "COM15"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "COM16"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "COM17"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "COM18"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "COM19"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "COM20"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "NO"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "COM1"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "COM2"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "COM3"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "COM4"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "COM5"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "COM6"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "COM7"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "COM8"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "COM9"))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "COM10"))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "COM11"))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "COM12"))
        self.comboBox_5.setItemText(13, _translate("MainWindow", "COM13"))
        self.comboBox_5.setItemText(14, _translate("MainWindow", "COM15"))
        self.comboBox_5.setItemText(15, _translate("MainWindow", "COM16"))
        self.comboBox_5.setItemText(16, _translate("MainWindow", "COM17"))
        self.comboBox_5.setItemText(17, _translate("MainWindow", "COM18"))
        self.comboBox_5.setItemText(18, _translate("MainWindow", "COM19"))
        self.comboBox_5.setItemText(19, _translate("MainWindow", "COM20"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "NO"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "COM1"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "COM2"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "COM3"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "COM4"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "COM5"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "COM6"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "COM7"))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "COM8"))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "COM9"))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "COM10"))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "COM11"))
        self.comboBox_6.setItemText(12, _translate("MainWindow", "COM12"))
        self.comboBox_6.setItemText(13, _translate("MainWindow", "COM13"))
        self.comboBox_6.setItemText(14, _translate("MainWindow", "COM15"))
        self.comboBox_6.setItemText(15, _translate("MainWindow", "COM16"))
        self.comboBox_6.setItemText(16, _translate("MainWindow", "COM17"))
        self.comboBox_6.setItemText(17, _translate("MainWindow", "COM18"))
        self.comboBox_6.setItemText(18, _translate("MainWindow", "COM19"))
        self.comboBox_6.setItemText(19, _translate("MainWindow", "COM20"))
        self.label_4.setText(_translate("MainWindow", "Baud Rate"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "1200"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "2400"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "4800"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "9600"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "19200"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "38400"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "57600"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "115200"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_8.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_8.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_8.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_8.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_8.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_8.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_8.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_8.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_8.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_8.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_8.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_8.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_8.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_8.setItemText(19, _translate("MainWindow", "20"))

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
